### ISSUE TITLE
Deck as opaque type?

### ISSUE THREAD

**Issue by battermann** [sudo-rushil/elm-cards#1]
Do you think it would be a good idea to make the type Deck opaque?

Then it would be possible to create a tagged type for a shuffled deck, e.g. and provide more type safety.

There could be a all sorts of convenient functions like `draw` function e.g.:

```elm
draw : ShuffledDeck -> (Card, ShuffledDeck)
```

I would be happy to collaborate on this.

**Comment by sudo-rushil** [comment]
That's an interesting idea! Just for clarification, do you mean something like the following?

```elm
type Deck = Deck (List Card)

type ShuffledDeck = ShuffledDeck Deck
```

**Comment by battermann** [comment]
That is exactly what I had in mind. Also I would then not export the constructor, but instead offer functions to construct instances and to access internals etc.

**Comment by sudo-rushil** [comment]
Got it. I'll take a look at it tonight after I finish up some work.

**Comment by battermann** [comment]
I'm happy to review, discuss, contribute if necessary.

**Comment by sudo-rushil** [comment]
If you could, I'd appreciate any feedback on the changes. I'm planning on building out the API a little more later on.
