### ISSUE TITLE
length would be nice

### ISSUE THREAD

**Issue by fonzerelly** [sudo-rushil/elm-cards#3]
hi rushil,

we were happy to find your module, to implement a small magic card trick with it. But for that we need to calculate with different deck sizes. And unfortunately there is no length method in your lib, which forces us to turn each deck into List Cards with getCards to get the length of the deck.
So a length method would be nice. Maybe I will fork your lib and create that function myself.

Thanx
Regards fonzerelly

**Comment by sudo-rushil** [comment]
I've added the length function to release 3.2.0.

**Comment by fonzerelly** [comment]
Great ! :D Thanx a lot
